export ZSH="/Users/$USER/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# ZSH Plugins
plugins=(
  git
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Exporting rest of envs (and config/API keys)
#
# DO NOT COMMIT SENSITIVE KEY/SECRET
#
export NVM_DIR="$HOME/.nvm"
  . "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
export GOPATH="$HOME/go"

